name: build

on: [push, pull_request]

jobs:
  fmt:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "15.14.0"

      - name: Install yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn build
